### ISSUE TITLE
Segmentation fault with PHP 8.1 in extract_body using MAILPARSE_EXTRACT_RETURN

### ISSUE THREAD

**Issue by larsnystrom** [php/pecl-mail-mailparse#19]
If you run the following PHP script it will end with exit code 139. The script is a minimal reproduction of some production code which causes a segmentation fault.

The line `// require __DIR__ . "/vendor/autoload.php";` is not necessary to trigger the issue, however when I uncomment this line in my project the var_dumped message is suffixed by some binary junk which changes on each run. This seems to indicate an out-of-bounds read somewhere.

Tested and reproduced with PHP 8.1.2 (cli).
PHP 8.0.15 (cli) is not affected, the issue seems to have been introduced with PHP 8.1.

```php
<?php

// require __DIR__ . "/vendor/autoload.php";

$original = <<<TXT
From: "Saved by Windows Internet Explorer 8"
Subject:
Date: Wed, 14 May 2014 12:34:56 +0200
MIME-Version: 1.0
Content-Type: text/html;
    charset="Windows-1252"
Content-Transfer-Encoding: quoted-printable
X-MimeOLE: Produced By Microsoft MimeOLE V6.1.7601.17609

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML><HEAD>
<META content=3D"text/html; charset=3Dwindows-1252" =
http-equiv=3DContent-Type>
<META name=3DGENERATOR content=3D"MSHTML 8.00.7601.18404"></HEAD>
<BODY></BODY></HTML>

TXT;

function dump(...$args)
{
    foreach ($args as $arg) {
        var_dump($arg);
    }
}

$msg      = new \MimeMessage("var", $original);
$contents = $msg->extract_body(\MAILPARSE_EXTRACT_RETURN);

dump($contents);

exit(0);
```

**Comment by jstanden** [comment]
I'm having the same issue in @cerb with Mailparse on PHP 8.1.2.

If I use `MAILPARSE_EXTRACT_STREAM` then it works as expected, but `MAILPARSE_EXTRACT_RETURN` returns a string with `PHP_INT_MAX` length that segfaults as soon as that variable is read.

Interestingly, the basic Mailparse example from this repo's README doesn't segfault in PHP 8.1.2.

**Comment by jstanden** [comment]
@cmb69 @remicollet I'm happy to sponsor a maintainer on this one.

**Comment by remicollet** [comment]
Can reproduce

Should be fixed by dca513d1870bbd5b3e92e5c8e2ac2e8154c8adc0 and c53ff5625433b360abc7109e02d58c73d8a63e10
Can you please check if this is ok for you ?

**Comment by remicollet** [comment]
Simpler fix in 36807106310ceeade795a3091dfff3a6a4564c28

**Comment by remicollet** [comment]
Version 3.1.3 is released

**Comment by jstanden** [comment]
@remicollet Great! I'll test this now and let you know.

I just sent a donation sent through your bio website. Thanks for all your hard work in maintaining these extensions.

**Comment by jstanden** [comment]
The fix looks good here. We're all set.
