### ISSUE TITLE
MimeMessage::__construct() throws TypeError with $mode=stream

### ISSUE THREAD

**Issue by akamah** [php/pecl-mail-mailparse#27]
I have read [this section of README.md](https://github.com/php/pecl-mail-mailparse/blob/7f58ef4910fdc6a41f15527a4aa1e16cbdb6cdfd/README.md?plain=1#L26-L30) and tried the following code:

```php
<?php
$fp = fopen("tests/testdata/uue.txt", "r");
$msg = new MimeMessage("stream", $fp);
var_dump($msg);
```

But resulted in the following TypeError:
```
PHP Fatal error:  Uncaught TypeError: mimemessage::__construct(): supplied argument is not a valid stream resource in /Users/akm/repo/pecl-mail-mailparse/test.php:3
Stack trace:
#0 /Users/akm/repo/pecl-mail-mailparse/test.php(3): mimemessage->__construct()
#1 {main}
  thrown in /Users/akm/repo/pecl-mail-mailparse/test.php on line 3
```

I confirmed it works correctly when the mode is `'file'`:
```php
<?php
$msg = new MimeMessage("file", "tests/testdata/uue.txt");
var_dump($msg);
```
Output:
```
class mimemessage#1 (2) {
  public $data =>
  array(11) {
    'headers' =>
...
```

I expect the MimeMessage object can be initialized correctly even if `$mode` is `'stream'`.

### Environment
- mailparse version: 3.1.4
- PHP Version: 8.1.13
- Operating System: macOS 12.5.1

**Comment by akamah** [comment]
I think we don't need the following line to convert the argument into string but I'm not sure.
https://github.com/php/pecl-mail-mailparse/blob/7f58ef4910fdc6a41f15527a4aa1e16cbdb6cdfd/mailparse.c#L284

**Comment by remicollet** [comment]
> I think we don't need the following line to convert the argument into string but I'm not sure.

INdeed.

**Comment by remicollet** [comment]
Please test from git
