### ISSUE TITLE
  PHP Startup: mailparse: Unable to initialize module

### ISSUE THREAD

**Issue by napengam** [php/pecl-mail-mailparse#28]
This used to work with PHP 8.1, upgraded to PHP 8.2.5 now I get this. 
What am I doing wrong ?

Warning: PHP Startup: mailparse: Unable to initialize module
Module compiled with module API=20210902
PHP    compiled with module API=20220829

**Comment by Jan-E** [comment]
Recompile it for PHP 8.2. For Windows: download a new one at https://www.apachelounge.com/viewtopic.php?t=6359

**Comment by napengam** [comment]
Sorry I still don't get it, I am probably too old ....
What do I have to recompile ? What should i download ?
I am lost !
