### ISSUE TITLE
GH29.phpt is missing

### ISSUE THREAD

**Issue by briaznar** [php/pecl-mail-mailparse#33]
Hi, 
Is it possible that you forgot to push `gh29.phpt `or to remove it from `package.xml`
I am getting the following on installation 

```
invalid package name/package file "package.xml"
install failed
ERROR: file ./tests/gh29.phpt does not exist
```

**Comment by remicollet** [comment]
Indeed, fixed now

**Comment by briaznar** [comment]
thanks :)
