### ISSUE TITLE
Provide php_mailparse.dll for php Version 8.2 and 8.3

### ISSUE THREAD

**Issue by reeperbahnause** [php/pecl-mail-mailparse#36]
Currently the mailparse extension can be downloaded at pecl for Windows up to php version 8.1.
Using the Github Actions it should be possible to provide the extension without pecl.
I will try to provide a PR which will build and upload the artifacts.

**Comment by reeperbahnause** [comment]
#37

**Comment by hostaway-greg** [comment]
Any update on this?

**Comment by cmb69** [comment]
DLLs for PHP 8.2 and 8.3 are available now https://pecl.php.net/package/mailparse/3.1.6/windows. If DLLs will be missing in the future, just file a ticket at https://github.com/php/php-windows-builder.
